package com.soumyajit.gradlemc.task;

public enum EvidenceType { ENVIRONMENT, INSTALLED_MODS, MEMORY, FPS, TPS_MSPT, ENTITIES, BLOCK_ENTITIES, WORLDGEN, CONFIGURATION, TASK_EXECUTION, WORKFLOW_EXECUTION, STABILITY }
