package com.soumyajit.gradlemc.foundation;
import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicInteger;

/** Small lifecycle-owned executor. Only immutable snapshots/evidence may cross to BACKGROUND_SAFE tasks. */
public final class FoundationEngine implements AutoCloseable {
 private final TaskRegistry registry;private final TaskHistory history;private final ThreadPoolExecutor workers;private final Map<TaskId,TaskCore.TaskResult> latest=new HashMap<>();private TaskCore.CancellationToken active;
 public FoundationEngine(TaskRegistry registry){this.registry=Objects.requireNonNull(registry);history=new TaskHistory(64);AtomicInteger n=new AtomicInteger();workers=new ThreadPoolExecutor(1,2,30,TimeUnit.SECONDS,new ArrayBlockingQueue<>(16),r->{Thread t=new Thread(r,"GradleMC-diagnostic-"+n.incrementAndGet());t.setDaemon(true);return t;},new ThreadPoolExecutor.AbortPolicy());workers.allowCoreThreadTimeOut(true);}
 public synchronized TaskCore.Plan dryRun(TaskId id,TaskCore.Context context,boolean force){return registry.plan(List.of(id),context,force);}
 public synchronized Optional<TaskCore.CancellationToken> activeExecution(){return Optional.ofNullable(active);}
 public synchronized boolean cancelActive(){return active!=null&&active.cancel();}
 public synchronized List<TaskCore.TaskResult> history(){return history.recent();}
 public List<TaskCore.TaskResult> execute(TaskId id,TaskCore.Context input,boolean force){TaskCore.CancellationToken token=new TaskCore.CancellationToken();synchronized(this){if(active!=null)throw new IllegalStateException("A diagnostic execution is already active");active=token;}try{TaskCore.Context context=new TaskCore.Context(input.clock(),token,input.staticFingerprint(),input.runtimeFingerprint(),Map.of());TaskCore.Plan plan=registry.plan(List.of(id),context,force);Map<TaskId,TaskCore.TaskResult> run=new HashMap<>();List<TaskCore.TaskResult> results=new ArrayList<>();for(TaskCore.PlanNode node:plan.nodes()){TaskCore.TaskResult result=executeNode(node,context,run,force);run.put(node.id(),result);results.add(result);synchronized(this){latest.put(node.id(),result);history.add(result);}}return List.copyOf(results);}finally{synchronized(this){active=null;}}}
 private TaskCore.TaskResult executeNode(TaskCore.PlanNode node,TaskCore.Context base,Map<TaskId,TaskCore.TaskResult> run,boolean force){TaskCore.Definition task=registry.get(node.id()).orElseThrow();Instant queued=base.clock().instant();if(base.cancellation().cancelled())return result(task,TaskCore.State.CANCELLED,queued,null,base.clock().instant(),"Cancelled before execution",base,null);if(!node.availability().available())return result(task,TaskCore.State.UNAVAILABLE,queued,null,base.clock().instant(),node.availability().reason(),base,null);for(TaskId dependency:task.dependencies()){TaskCore.TaskResult previous=run.get(dependency);if(previous==null||previous.state()!=TaskCore.State.SUCCEEDED)return result(task,TaskCore.State.SKIPPED,queued,null,base.clock().instant(),"Skipped because dependency "+dependency+" did not succeed",base,null);}TaskCore.TaskResult cached; synchronized(this){cached=latest.get(task.id());}if(!force&&reusable(task,cached,base))return result(task,TaskCore.State.SUCCEEDED,queued,base.clock().instant(),base.clock().instant(),"Reused current process result",base,cached.output().orElse(null));Instant started=base.clock().instant();TaskCore.Context context=new TaskCore.Context(base.clock(),base.cancellation(),base.staticFingerprint(),base.runtimeFingerprint(),run);try{TaskCore.Output out;if(task.affinity()==TaskCore.Affinity.BACKGROUND_SAFE){Future<TaskCore.Output> f=workers.submit(()->task.body().run(context));try{out=f.get(task.timeout().toMillis(),TimeUnit.MILLISECONDS);}catch(TimeoutException e){base.cancellation().cancel();f.cancel(true);return result(task,TaskCore.State.TIMED_OUT,queued,started,base.clock().instant(),"Timed out after "+task.timeout().toMillis()+" ms",base,null);}}else{out=task.body().run(context);if(Duration.between(started,base.clock().instant()).compareTo(task.timeout())>0){base.cancellation().cancel();return result(task,TaskCore.State.TIMED_OUT,queued,started,base.clock().instant(),"Timeout requested; caller-thread work was not forcibly stopped",base,null);}}if(base.cancellation().cancelled())return result(task,TaskCore.State.CANCELLED,queued,started,base.clock().instant(),"Cancelled cooperatively",base,null);return result(task,TaskCore.State.SUCCEEDED,queued,started,base.clock().instant(),"Completed",base,out);}catch(InterruptedException e){Thread.currentThread().interrupt();return result(task,TaskCore.State.CANCELLED,queued,started,base.clock().instant(),"Interrupted while cancellation was requested",base,null);}catch(ExecutionException|RejectedExecutionException e){return result(task,TaskCore.State.FAILED,queued,started,base.clock().instant(),"Execution failed: "+e.getClass().getSimpleName(),base,null);}catch(Exception e){return result(task,TaskCore.State.FAILED,queued,started,base.clock().instant(),"Execution failed: "+e.getClass().getSimpleName(),base,null);}}
 private static boolean reusable(TaskCore.Definition task,TaskCore.TaskResult old,TaskCore.Context now){if(old==null||old.state()!=TaskCore.State.SUCCEEDED||task.cachePolicy()==TaskCore.CachePolicy.NEVER_CACHE||task.cachePolicy()==TaskCore.CachePolicy.ALWAYS_RUN)return false;if(task.cachePolicy()==TaskCore.CachePolicy.STATIC_FINGERPRINT)return old.staticFingerprint().equals(Optional.of(now.staticFingerprint()));if(task.cachePolicy()==TaskCore.CachePolicy.RUNTIME_CONTEXT)return old.runtimeFingerprint().equals(Optional.of(now.runtimeFingerprint()));return task.cachePolicy()==TaskCore.CachePolicy.PROCESS_LIFETIME;}
 private static TaskCore.TaskResult result(TaskCore.Definition task,TaskCore.State state,Instant queued,Instant started,Instant completed,String reason,TaskCore.Context context,TaskCore.Output output){List<String> ids=output==null?List.of():output.evidence().stream().map(Evidence::id).toList();Freshness f=new Freshness(state==TaskCore.State.SUCCEEDED?Freshness.State.FRESH:Freshness.State.UNAVAILABLE,completed,Optional.empty(),"task-engine",reason,List.of());return new TaskCore.TaskResult(task.id(),state,queued,started,completed,reason,List.of(),state==TaskCore.State.FAILED?List.of(reason):List.of(),ids,f,Optional.of(context.staticFingerprint()),Optional.of(context.runtimeFingerprint()),Optional.ofNullable(output));}
 @Override public void close(){cancelActive();workers.shutdown();try{if(!workers.awaitTermination(2,TimeUnit.SECONDS))workers.shutdownNow();}catch(InterruptedException e){Thread.currentThread().interrupt();workers.shutdownNow();}}
}
