package com.soumyajit.gradlemc.foundation;

import java.time.*; import java.util.*; import java.util.concurrent.atomic.AtomicBoolean;

public final class TaskCore { private TaskCore(){}
 public enum State { NOT_RUN, QUEUED, RUNNING, SUCCEEDED, FAILED, CANCELLED, TIMED_OUT, SKIPPED, UNAVAILABLE, STALE }
 /**
  * Explicit task ownership.  A capture task may only create an immutable snapshot on its owning
  * game thread; analysis and serialization must use {@link #WORKER_SAFE}.  The unavailable value
  * makes side restrictions visible in plans instead of quietly falling back to another thread.
  */
 public enum Affinity { SERVER_MAIN_THREAD_CAPTURE, CLIENT_MAIN_THREAD_CAPTURE, WORKER_SAFE, CALLER_SAFE, UNAVAILABLE_ON_THIS_SIDE }
 public enum CachePolicy { NEVER_CACHE, PROCESS_LIFETIME, STATIC_FINGERPRINT, RUNTIME_CONTEXT, TIME_BOUND, ALWAYS_RUN }
 public enum Reason { REQUESTED_DIRECTLY, REQUIRED_DEPENDENCY, CACHE_MISS, STALE_OUTPUT, CONTEXT_CHANGED, FORCED_REFRESH, NO_PREVIOUS_RESULT, DEPENDENCY_FAILED, UNAVAILABLE }
 public record CancellationToken(AtomicBoolean requested) { public CancellationToken(){this(new AtomicBoolean());} public boolean cancel(){return requested.compareAndSet(false,true);} public boolean cancelled(){return requested.get();} }
 public record Availability(boolean available,String reason) { public Availability {reason=reason==null?"":reason;} public static Availability present(){return new Availability(true,"");} public static Availability unavailable(String reason){return new Availability(false,reason);} }
 public record Output(List<Evidence> evidence,String summary) { public Output {evidence=evidence==null?List.of():List.copyOf(evidence);if(evidence.size()>32)throw new IllegalArgumentException("Too many evidence items");summary=summary==null?"":summary;} }
 public record Context(Clock clock,CancellationToken cancellation,StaticFingerprint staticFingerprint,RuntimeContextFingerprint runtimeFingerprint,Map<TaskId,TaskResult> dependencies,Set<String> capabilities) { public Context {clock=clock==null?Clock.systemUTC():clock;cancellation=cancellation==null?new CancellationToken():cancellation;dependencies=Map.copyOf(dependencies==null?Map.of():dependencies);capabilities=Set.copyOf(capabilities==null?Set.of():capabilities);if(capabilities.stream().anyMatch(x->x==null||!x.matches("[a-z0-9][a-z0-9-]{0,63}")))throw new IllegalArgumentException("Invalid Foundation capability");} public Context(Clock clock,CancellationToken cancellation,StaticFingerprint staticFingerprint,RuntimeContextFingerprint runtimeFingerprint,Map<TaskId,TaskResult> dependencies){this(clock,cancellation,staticFingerprint,runtimeFingerprint,dependencies,Set.of());} }
 @FunctionalInterface public interface Body { Output run(Context context) throws Exception; }
 public record Definition(TaskId id,String displayName,String category,List<TaskId> dependencies,Affinity affinity,Duration timeout,CachePolicy cachePolicy,java.util.function.Function<Context,Availability> availability,Body body) { public Definition {if(id==null||Evidence.blank(displayName)||Evidence.blank(category)||affinity==null||timeout==null||timeout.isZero()||timeout.isNegative()||timeout.compareTo(Duration.ofMinutes(5))>0||cachePolicy==null||availability==null||body==null)throw new IllegalArgumentException("Invalid task definition");dependencies=List.copyOf(dependencies==null?List.of():dependencies);if(dependencies.size()>32)throw new IllegalArgumentException("Too many dependencies");} }
 public record TaskResult(TaskId id,State state,Instant queuedAt,Instant startedAt,Instant completedAt,String reason,List<String> warnings,List<String> errors,List<String> evidenceIds,Freshness freshness,Optional<StaticFingerprint> staticFingerprint,Optional<RuntimeContextFingerprint> runtimeFingerprint,Optional<Output> output) { public TaskResult {reason=reason==null?"":reason;warnings=Evidence.boundedList(warnings,16);errors=Evidence.boundedList(errors,16);evidenceIds=Evidence.boundedList(evidenceIds,32);staticFingerprint=staticFingerprint==null?Optional.empty():staticFingerprint;runtimeFingerprint=runtimeFingerprint==null?Optional.empty():runtimeFingerprint;output=output==null?Optional.empty():output;} public Duration duration(){return startedAt==null||completedAt==null?Duration.ZERO:Duration.between(startedAt,completedAt);} }
 public record PlanNode(TaskId id,List<TaskId> dependencies,boolean wouldRun,List<Reason> reasons,Availability availability,String explanation) { public PlanNode {dependencies=List.copyOf(dependencies);reasons=List.copyOf(reasons);explanation=explanation==null?"":explanation;} }
 public record Plan(List<TaskId> requested,List<PlanNode> nodes,List<String> blockers) { public Plan {requested=List.copyOf(requested);nodes=List.copyOf(nodes);blockers=List.copyOf(blockers);} }
}
