package com.soumyajit.gradlemc.investigation;
import java.time.Instant;import java.util.*;
/** Immutable, allowlisted persistence boundary; no Minecraft objects or absolute paths cross it. */
public record InvestigationManifest(int schemaVersion,long revision,InvestigationId id,InvestigationProfileId profileId,String profileVersion,InvestigationState state,Instant createdAt,Instant startedAt,Instant endedAt,InvestigationRuntimeIdentity runtimeIdentity,String inputFingerprint,List<InvestigationStepRecord> steps,List<InvestigationEvidenceRef> evidence,List<InvestigationLimitation> limitations,Optional<InvestigationFailure> failure,boolean truncated,List<String> truncationReasons,int redactionSchemaVersion,boolean comparisonEligible) {
 public static final int SCHEMA_VERSION=1, MAX_STEPS=128,MAX_EVIDENCE=256,MAX_LIMITATIONS=64,MAX_REASONS=32;
 public InvestigationManifest { if(schemaVersion!=SCHEMA_VERSION||revision<0||id==null||profileId==null||state==null||createdAt==null||runtimeIdentity==null||redactionSchemaVersion<=0)throw new IllegalArgumentException("Invalid manifest header");profileVersion=InvestigationText.safe(profileVersion);inputFingerprint=InvestigationText.safe(inputFingerprint);steps=copy(steps,MAX_STEPS,"steps");evidence=copy(evidence,MAX_EVIDENCE,"evidence");limitations=copy(limitations,MAX_LIMITATIONS,"limitations");failure=failure==null?Optional.empty():failure;truncationReasons=copyStrings(truncationReasons,MAX_REASONS,"truncation reasons");validateState(state,createdAt,startedAt,endedAt,limitations,failure,truncated,truncationReasons,comparisonEligible); }
 private static <T> List<T> copy(List<T> values,int max,String name){if(values==null||values.size()>max||values.stream().anyMatch(Objects::isNull))throw new IllegalArgumentException("Invalid "+name);return List.copyOf(values);} private static List<String> copyStrings(List<String> values,int max,String name){if(values==null||values.size()>max)throw new IllegalArgumentException("Invalid "+name);List<String> out=new ArrayList<>();for(String value:values)out.add(InvestigationText.safe(value));return List.copyOf(out);}
 private static void validateState(InvestigationState s,Instant created,Instant start,Instant end,List<InvestigationLimitation> limits,Optional<InvestigationFailure> failure,boolean truncated,List<String> reasons,boolean comparisonEligible){if(start!=null&&start.isBefore(created)||end!=null&&(end.isBefore(created)||start!=null&&end.isBefore(start)))throw new IllegalArgumentException("Invalid manifest timestamps");if(s==InvestigationState.CREATED&&(start!=null||end!=null))throw new IllegalArgumentException("created manifest timestamps");if(s==InvestigationState.RUNNING&&(start==null||end!=null))throw new IllegalArgumentException("running manifest timestamps");if(s.terminal()&&end==null)throw new IllegalArgumentException("terminal manifest needs end");if((s==InvestigationState.COMPLETED||s==InvestigationState.COMPLETED_WITH_LIMITATIONS)&&failure.filter(InvestigationFailure::fatal).isPresent())throw new IllegalArgumentException("successful manifest cannot be fatal");if(s==InvestigationState.COMPLETED_WITH_LIMITATIONS&&limits.isEmpty()&&!truncated)throw new IllegalArgumentException("limited completion needs limitation");if(s==InvestigationState.FAILED&&failure.isEmpty())throw new IllegalArgumentException("failed manifest needs failure");if(s==InvestigationState.CANCELLED&&comparisonEligible)throw new IllegalArgumentException("cancelled manifest cannot compare");if(truncated&&reasons.isEmpty())throw new IllegalArgumentException("truncation needs reason");}
}
