package com.soumyajit.gradlemc.report;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.api.Assumptions;
import java.nio.file.*;
import java.nio.file.attribute.FileTime;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import static org.junit.jupiter.api.Assertions.*;

class LocalReportIndexTest {
    @TempDir Path temp;
    private LocalReportIndex.Root root(LocalReportIndex.Kind kind) throws Exception { Path reports=Files.createDirectories(temp.resolve("reports")); return new LocalReportIndex.Root(kind,reports,Set.of("gradlemc-"),Set.of(".txt")); }
    private Path write(String name) throws Exception { Path value=Files.createDirectories(temp.resolve("reports")).resolve(name); Files.writeString(value,"first\nsecond\nthird\n"); return value; }
    @Test void emptyRootIsNotGenerated() throws Exception { var catalog=LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))); assertEquals(LocalReportIndex.State.NOT_GENERATED,catalog.state(LocalReportIndex.Kind.FPS)); }
    @Test void unavailableRootIsReported() { var catalog=LocalReportIndex.scan(List.of(new LocalReportIndex.Root(LocalReportIndex.Kind.FPS,temp.resolve("missing"),Set.of("gradlemc-"),Set.of(".txt")))); assertEquals(LocalReportIndex.State.OUTPUT_ROOT_UNAVAILABLE,catalog.state(LocalReportIndex.Kind.FPS)); }
    @Test void oneValidReportIsAvailable() throws Exception { write("gradlemc-one.txt"); var catalog=LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))); assertEquals(1,catalog.entries().get(LocalReportIndex.Kind.FPS).size()); }
    @Test void categoriesStaySeparate() throws Exception { write("gradlemc-fps.txt"); var perf=root(LocalReportIndex.Kind.PERFORMANCE); var catalog=LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS),perf)); assertTrue(catalog.latest(LocalReportIndex.Kind.FPS).isPresent()); assertTrue(catalog.latest(LocalReportIndex.Kind.PERFORMANCE).isPresent()); }
    @Test void latestUsesModifiedTime() throws Exception { var first=write("gradlemc-a.txt"); var second=write("gradlemc-b.txt"); Files.setLastModifiedTime(first,FileTime.from(Instant.ofEpochMilli(10))); Files.setLastModifiedTime(second,FileTime.from(Instant.ofEpochMilli(20))); assertEquals("gradlemc-b.txt",LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).latest(LocalReportIndex.Kind.FPS).orElseThrow().displayName()); }
    @Test void equalTimesUseNameTieBreak() throws Exception { var first=write("gradlemc-a.txt"); var second=write("gradlemc-b.txt"); var time=FileTime.from(Instant.ofEpochMilli(20)); Files.setLastModifiedTime(first,time); Files.setLastModifiedTime(second,time); assertEquals("gradlemc-b.txt",LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).latest(LocalReportIndex.Kind.FPS).orElseThrow().displayName()); }
    @Test void latestOverallIsDeterministic() throws Exception { var first=write("gradlemc-a.txt"); var second=write("gradlemc-b.txt"); Files.setLastModifiedTime(first,FileTime.fromMillis(1)); Files.setLastModifiedTime(second,FileTime.fromMillis(2)); var catalog=LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))); assertEquals("gradlemc-b.txt",catalog.latestOverall().orElseThrow().displayName()); }
    @Test void deletedIndexedFileIsNotActionable() throws Exception { var file=write("gradlemc-one.txt"); var index=LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))); Files.delete(file); assertEquals(LocalReportIndex.State.INDEXED_FILE_MISSING,LocalReportIndex.validateFor(index.latestOverall().orElseThrow(),List.of(root(LocalReportIndex.Kind.FPS)),LocalReportIndex.Action.COPY_PATH)); }
    @Test void replacedIndexedFileRemainsBounded() throws Exception { var file=write("gradlemc-one.txt"); var entry=LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).latestOverall().orElseThrow(); Files.writeString(file,"x".repeat((int)LocalReportIndex.MAX_SUMMARY_FILE_BYTES+1)); assertEquals(LocalReportIndex.State.UNSUPPORTED_FORMAT,LocalReportIndex.validateFor(entry,List.of(root(LocalReportIndex.Kind.FPS)),LocalReportIndex.Action.VIEW_SUMMARY)); }
    @Test void unsupportedExtensionIsIgnored() throws Exception { Files.writeString(Files.createDirectories(temp.resolve("reports")).resolve("gradlemc-one.exe"),"x"); assertEquals(LocalReportIndex.State.NOT_GENERATED,LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).state(LocalReportIndex.Kind.FPS)); }
    @Test void directoryIsNotAReport() throws Exception { Files.createDirectories(temp.resolve("reports").resolve("gradlemc-dir.txt")); assertTrue(LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).latestOverall().isEmpty()); }
    @Test void traversalEntryIsRejected() throws Exception { var reportRoot=root(LocalReportIndex.Kind.FPS); Path outside=Files.writeString(temp.resolve("outside.txt"),"x"); var entry=new LocalReportIndex.Entry(LocalReportIndex.Kind.FPS,outside.getParent().resolve("reports").resolve("..").resolve("outside.txt"),"outside.txt",Instant.now(),1,true); assertEquals(LocalReportIndex.State.INDEXED_FILE_MISSING,LocalReportIndex.validateFor(entry,List.of(reportRoot),LocalReportIndex.Action.COPY_PATH)); }
    @Test void absoluteUntrustedEntryIsRejected() throws Exception { var reportRoot=root(LocalReportIndex.Kind.FPS); Path outside=Files.writeString(temp.resolve("outside.txt"),"x"); var entry=new LocalReportIndex.Entry(LocalReportIndex.Kind.FPS,outside,"outside.txt",Instant.now(),1,true); assertEquals(LocalReportIndex.State.INDEXED_FILE_MISSING,LocalReportIndex.validateFor(entry,List.of(reportRoot),LocalReportIndex.Action.COPY_PATH)); }
    @Test void linkEscapeIsRejectedWhenSupported() throws Exception { var reportRoot=root(LocalReportIndex.Kind.FPS); Path outside=Files.writeString(temp.resolve("outside.txt"),"x"); Path link=temp.resolve("reports").resolve("gradlemc-link.txt"); try { Files.createSymbolicLink(link,outside); } catch (UnsupportedOperationException | FileSystemException unavailable) { Assumptions.abort("symbolic links unavailable"); } assertTrue(LocalReportIndex.scan(List.of(reportRoot)).latestOverall().isEmpty()); }
    @Test void traversalDepthIsBounded() throws Exception { Files.createDirectories(temp.resolve("reports").resolve("one").resolve("two").resolve("three")); Files.writeString(temp.resolve("reports").resolve("one").resolve("two").resolve("three").resolve("gradlemc-deep.txt"),"x"); assertTrue(LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).latestOverall().isEmpty()); }
    @Test void retainedEntriesAreBounded() throws Exception { for(int i=0;i<LocalReportIndex.MAX_RETAINED_ENTRIES+5;i++) write(String.format("gradlemc-%03d.txt",i)); assertEquals(LocalReportIndex.MAX_RETAINED_ENTRIES,LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).entries().get(LocalReportIndex.Kind.FPS).size()); }
    @Test void summaryLineLimitIsBounded() throws Exception { Path file=write("gradlemc-many.txt"); Files.writeString(file,"line\n".repeat(50)); var entry=LocalReportIndex.scan(List.of(root(LocalReportIndex.Kind.FPS))).latestOverall().orElseThrow(); assertEquals(LocalReportIndex.MAX_SUMMARY_LINES,LocalReportIndex.readSummary(entry,List.of(root(LocalReportIndex.Kind.FPS))).size()); }
    @Test void summaryActionRequiresTextFormat() throws Exception { Path bundles=Files.createDirectories(temp.resolve("bundles")); Path zip=Files.writeString(bundles.resolve("gradlemc-bundle.zip"),"x"); var reportRoot=new LocalReportIndex.Root(LocalReportIndex.Kind.ISSUE_BUNDLE,bundles,Set.of("gradlemc-"),Set.of(".zip")); var entry=LocalReportIndex.scan(List.of(reportRoot)).latestOverall().orElseThrow(); assertEquals(LocalReportIndex.State.UNSUPPORTED_FORMAT,LocalReportIndex.validateFor(entry,List.of(reportRoot),LocalReportIndex.Action.VIEW_SUMMARY)); }
    @Test void copyPathRequiresSafeLocalFile() throws Exception { write("gradlemc-one.txt"); var reportRoot=root(LocalReportIndex.Kind.FPS); var entry=LocalReportIndex.scan(List.of(reportRoot)).latestOverall().orElseThrow(); assertEquals(LocalReportIndex.State.AVAILABLE,LocalReportIndex.validateFor(entry,List.of(reportRoot),LocalReportIndex.Action.COPY_PATH)); }
}
