package com.soumyajit.gradlemc.storage;

import com.soumyajit.gradlemc.util.GradleMcPaths;
import com.soumyajit.gradlemc.util.ManagedPathSafety;
import java.io.IOException;import java.nio.file.*;import java.time.*;import java.util.*;
public final class StorageDiagnostics{private static final int MAX_FILES=2048,MAX_CLEANUP=256;private static final long LARGE=16L*1024*1024;private StorageDiagnostics(){}
    public static StorageSummary inspect(){Path game=GradleMcPaths.gameDirectory(),root=GradleMcPaths.gradleMcDirectory(),reports=GradleMcPaths.reportDirectory();List<String>large=new ArrayList<>(),temp=new ArrayList<>(),limits=new ArrayList<>();long bytes=0;int count=0;boolean writable=false;try{ManagedPathSafety.ensureDirectory(game,reports);Path probe=Files.createTempFile(reports,".storage-",".tmp");Files.delete(probe);writable=true;try(var files=Files.list(reports)){for(Path file:files.filter(p->Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(p)).limit(MAX_FILES+1L).toList()){if(count++==MAX_FILES){limits.add("report listing truncated at "+MAX_FILES);break;}long size=Files.size(file);bytes=saturating(bytes,size);if(size>LARGE)large.add(file.getFileName()+" ("+size+" bytes)");}}}catch(IOException e){limits.add("reports: "+e.getClass().getSimpleName());}
        for(Path dir:ownedDirectories()){if(!safeOwnedDirectory(game,dir))continue;try(var files=Files.list(dir)){for(Path file:files.filter(StorageDiagnostics::staleOwnedTemp).limit(MAX_CLEANUP).toList())temp.add(dir.getFileName()+"/"+file.getFileName());}catch(IOException e){limits.add(dir.getFileName()+": "+e.getClass().getSimpleName());}}
        limits.add("World save/autosave timing is unavailable without a supported save lifecycle boundary.");limits.add("No unrelated directory or whole-disk scan was performed.");return new StorageSummary(usable(game),usable(root),writable,bytes,count,large,temp,limits);}
    public static List<Path> cleanupCandidates(){List<Path> out=new ArrayList<>();Path game=GradleMcPaths.gameDirectory();for(Path dir:ownedDirectories()){if(!safeOwnedDirectory(game,dir))continue;try(var files=Files.list(dir)){out.addAll(files.filter(StorageDiagnostics::staleOwnedTemp).limit(MAX_CLEANUP-out.size()).toList());}catch(IOException ignored){}if(out.size()>=MAX_CLEANUP)break;}return List.copyOf(out);}
    public static int deleteCandidates()throws IOException{int deleted=0;Path root=GradleMcPaths.gradleMcDirectory().toAbsolutePath().normalize();for(Path candidate:cleanupCandidates()){Path value=candidate.toAbsolutePath().normalize();if(!value.startsWith(root)||Files.isSymbolicLink(value)||!Files.isRegularFile(value,LinkOption.NOFOLLOW_LINKS)||!value.getFileName().toString().endsWith(".tmp"))throw new IOException("Cleanup candidate failed ownership validation");if(Files.deleteIfExists(value))deleted++;}return deleted;}
    private static List<Path>ownedDirectories(){return List.of(GradleMcPaths.reportDirectory(),GradleMcPaths.exportDirectory(),GradleMcPaths.issueBundleDirectory(),GradleMcPaths.profileDirectory(),GradleMcPaths.experimentDirectory(),GradleMcPaths.incidentDirectory());}
    private static boolean safeOwnedDirectory(Path game,Path directory){try{ManagedPathSafety.ensureDirectory(game,directory);return true;}catch(IOException ignored){return false;}}
    private static boolean staleOwnedTemp(Path p){try{return Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(p)&&p.getFileName().toString().endsWith(".tmp")&&Files.getLastModifiedTime(p).toInstant().isBefore(Instant.now().minus(Duration.ofHours(24)));}catch(IOException e){return false;}}
    private static long usable(Path p){try{Path target=Files.exists(p)?p:p.getParent();return target==null?-1:Files.getFileStore(target).getUsableSpace();}catch(IOException e){return -1;}}private static long saturating(long a,long b){return a>Long.MAX_VALUE-b?Long.MAX_VALUE:a+b;}}
