package com.soumyajit.gradlemc.investigation.storage;
import com.soumyajit.gradlemc.investigation.*;import com.soumyajit.gradlemc.util.ManagedPathSafety;import java.io.*;import java.nio.file.*;import java.util.*;
/** Small owned-root store; callers provide immutable manifests and expected revisions. */
public final class InvestigationStore { public static final int MAX_DIRECTORY_SCAN=768;private final Path game;private final InvestigationManifestCodec manifests=new InvestigationManifestCodec();private final InvestigationIndexCodec indexes=new InvestigationIndexCodec();private final Map<InvestigationId,Object> manifestLocks=new java.util.concurrent.ConcurrentHashMap<>();private final Object indexLock=new Object();public InvestigationStore(Path game){this.game=Objects.requireNonNull(game).toAbsolutePath().normalize();}
 public boolean create(InvestigationManifest value)throws IOException{if(value.revision()!=0)throw new IllegalArgumentException("New manifests begin at revision zero");synchronized(lock(value.id())){InvestigationPaths.ensureSession(game,value.id());Path path=InvestigationPaths.manifest(game,value.id());if(Files.exists(path,LinkOption.NOFOLLOW_LINKS))throw new FileAlreadyExistsException("Investigation already exists");boolean fallback=AtomicUtf8File.write(path,manifests.encode(value));rebuildIndex();return fallback;}}
 public InvestigationManifest read(InvestigationId id)throws IOException{Path path=InvestigationPaths.requireManifest(game,id);return manifests.decode(readBounded(path,InvestigationManifestCodec.MAX_BYTES));}
 public boolean update(InvestigationManifest next,long expectedRevision,InvestigationState expectedState)throws IOException{synchronized(lock(next.id())){InvestigationManifest old=read(next.id());if(old.revision()!=expectedRevision||old.state()!=expectedState)throw new ConcurrentModificationException("Stale investigation revision or state");if(old.state().terminal())throw new IllegalStateException("Terminal investigation is immutable");InvestigationStateMachine.requireTransition(old.state(),next.state());if(next.revision()!=old.revision()+1)throw new IllegalArgumentException("Invalid next revision");if(!old.id().equals(next.id())||!old.profileId().equals(next.profileId())||!old.createdAt().equals(next.createdAt()))throw new IllegalArgumentException("Investigation identity is immutable");boolean fallback=AtomicUtf8File.write(InvestigationPaths.manifest(game,next.id()),manifests.encode(next));rebuildIndex();return fallback;}}
 public InvestigationRecoveryResult loadIndex()throws IOException{Path index=InvestigationPaths.index(game);if(Files.isRegularFile(index,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(index))try{return new InvestigationRecoveryResult(indexes.decode(readBounded(InvestigationPaths.requireIndex(game),InvestigationIndexCodec.MAX_BYTES)),false,List.of());}catch(IOException ignored){}return rebuildIndex();}
 /** Explicit recovery only: interrupted work is recorded as failed and is never resumed or rerun. */
 public RecoverySummary recoverInterrupted(int requestedCap)throws IOException{return recoverInterrupted(requestedCap,Set.of());}
 /** Locally active IDs are excluded so a manual recover cannot overwrite an in-memory session. */
 public RecoverySummary recoverInterrupted(int requestedCap,Set<InvestigationId> protectedIds)throws IOException{int cap=Math.max(1,Math.min(64,requestedCap));Set<InvestigationId> protectedCopy=Set.copyOf(protectedIds==null?Set.of():protectedIds);InvestigationRecoveryResult index=loadIndex();int recovered=0,skipped=0;List<String> diagnostics=new ArrayList<>(index.diagnostics());for(InvestigationIndexEntry entry:index.index().entries()){if(recovered>=cap){diagnostics.add("recovery-cap-reached");break;}if(entry.state().terminal())continue;if(protectedCopy.contains(entry.id())){skipped++;diagnostics.add("recovery-active-skipped-"+entry.id().value());continue;}try{InvestigationManifest old=read(entry.id());if(old.state().terminal())continue;List<InvestigationLimitation> limits=new ArrayList<>(old.limitations());limits.add(new InvestigationLimitation("interrupted-recovery","The server stopped before this investigation reached a terminal state; it was not rerun."));InvestigationManifest next=new InvestigationManifest(old.schemaVersion(),old.revision()+1,old.id(),old.profileId(),old.profileVersion(),InvestigationState.FAILED,old.createdAt(),old.startedAt(),java.time.Instant.now(),old.runtimeIdentity(),old.inputFingerprint(),old.steps(),old.evidence(),limits,Optional.of(new InvestigationFailure("interrupted-recovery","Investigation interrupted by a prior server shutdown.",true)),old.truncated(),old.truncationReasons(),old.redactionSchemaVersion(),false);update(next,old.revision(),old.state());recovered++;}catch(Exception exception){skipped++;diagnostics.add("recovery-skipped-"+entry.id().value()+":"+exception.getClass().getSimpleName());}}return new RecoverySummary(recovered,skipped,List.copyOf(diagnostics));}
 public InvestigationRecoveryResult rebuildIndex()throws IOException{synchronized(indexLock){Path root=InvestigationPaths.root(game);List<String> diagnostics=new ArrayList<>();List<InvestigationIndexEntry>entries=new ArrayList<>();Set<InvestigationId>seen=new HashSet<>();List<Path> candidates=new ArrayList<>();try(DirectoryStream<Path> children=Files.newDirectoryStream(root)){for(Path child:children){if(candidates.size()>=MAX_DIRECTORY_SCAN+1){diagnostics.add("directory-scan-truncated");break;}if(Files.isDirectory(child,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(child))candidates.add(child);}}candidates.sort(Comparator.comparing(path->path.getFileName().toString()));for(Path child:candidates){if(entries.size()>=InvestigationIndex.MAX_SESSIONS){diagnostics.add("index-entry-limit-reached");break;}try{InvestigationId id=new InvestigationId(child.getFileName().toString());InvestigationManifest m=manifests.decode(readBounded(ManagedPathSafety.requireRegularFile(root,child.resolve("manifest.json")),InvestigationManifestCodec.MAX_BYTES));if(!m.id().equals(id))throw new IOException("manifest ID mismatch");if(!seen.add(m.id()))throw new IOException("duplicate manifest ID");entries.add(new InvestigationIndexEntry(m.id(),m.profileId(),m.state(),m.createdAt(),m.endedAt(),m.revision()));}catch(Exception e){diagnostics.add("skipped-"+child.getFileName()+":"+e.getClass().getSimpleName());}}InvestigationIndex index=new InvestigationIndex(InvestigationIndex.SCHEMA_VERSION,entries);AtomicUtf8File.write(InvestigationPaths.index(game),indexes.encode(index));return new InvestigationRecoveryResult(index,true,diagnostics);}}
 private Object lock(InvestigationId id){return manifestLocks.computeIfAbsent(id,ignored->new Object());}
 private static byte[] readBounded(Path path,int max)throws IOException{if(max<1||!Files.isRegularFile(path,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(path))throw new IOException("Unavailable or unsafe investigation file");try(InputStream input=Files.newInputStream(path);ByteArrayOutputStream output=new ByteArrayOutputStream(Math.min(max,8192))){byte[] buffer=new byte[Math.min(8192,max+1)];int total=0,read;while((read=input.read(buffer))!=-1){if(read>max-total)throw new IOException("Investigation file exceeds safe size limit");output.write(buffer,0,read);total+=read;}return output.toByteArray();}}
 public record RecoverySummary(int recovered,int skipped,List<String> diagnostics){public RecoverySummary{diagnostics=List.copyOf(diagnostics==null?List.of():diagnostics);}}
}
