package com.soumyajit.gradlemc.diagnostics

import com.soumyajit.gradlemc.GradleMC
import com.soumyajit.gradlemc.config.GradleMcConfig
import com.soumyajit.gradlemc.config.GradleMcConfigSnapshot
import com.soumyajit.gradlemc.report.ReportFiles
import com.soumyajit.gradlemc.report.ReportPaths
import com.soumyajit.gradlemc.performance.PerformanceService
import com.soumyajit.gradlemc.performance.PerformanceSnapshot
import net.fabricmc.api.EnvType
import net.fabricmc.loader.api.FabricLoader
import net.minecraft.SharedConstants
import java.nio.file.Path
import java.time.Instant
import java.util.Locale

enum class DiagnosticSeverity { PASS, INFO, WARN, FAIL, CRITICAL }
data class EnvironmentSnapshot(val gradleMcVersion: String, val minecraftVersion: String, val loaderVersion: String, val javaVersion: String, val javaVendor: String, val operatingSystem: String, val architecture: String, val physicalSide: String, val installedModCount: Int, val mods: List<String>)
data class MemorySnapshot(val usedBytes: Long, val committedBytes: Long, val maxBytes: Long, val freeHeadroomBytes: Long, val usedPercent: Double, val pressure: DiagnosticSeverity, val collectedAt: Instant) { val usedMiB get() = usedBytes / MEBIBYTE; val committedMiB get() = committedBytes / MEBIBYTE; val maxMiB get() = maxBytes / MEBIBYTE; val freeMiB get() = freeHeadroomBytes / MEBIBYTE; companion object { const val MEBIBYTE = 1024L * 1024L } }
data class StabilityFinding(val severity: DiagnosticSeverity, val title: String, val detail: String, val suggestion: String = "")
data class StabilityCheckResult(val ranAt: Instant, val findings: List<StabilityFinding>) { val highestSeverity get() = findings.maxByOrNull { it.severity.ordinal }?.severity ?: DiagnosticSeverity.INFO; val summary get() = findings.groupingBy { it.severity }.eachCount().entries.sortedBy { it.key.ordinal }.joinToString(", ") { "${it.value} ${it.key.name.lowercase()}" } }
data class DiagnosticSnapshot(val collectedAt: Instant, val environment: EnvironmentSnapshot, val memory: MemorySnapshot, val performance: PerformanceSnapshot, val configuration: GradleMcConfigSnapshot, val latestReport: Path?, val lastChecks: StabilityCheckResult?)
sealed interface ReportExportResult { data class Success(val paths: List<Path>, val displayPaths: List<String>) : ReportExportResult; data class Failure(val message: String, val cause: Throwable? = null) : ReportExportResult }
sealed interface LatestReportResult { data class Found(val path: Path, val displayPath: String) : LatestReportResult; data object Empty : LatestReportResult; data class Failure(val message: String) : LatestReportResult }
data class SmartDiagnosticsResult(val score: Int, val advice: List<String>, val message: String, val basedOn: StabilityCheckResult)

object DiagnosticsService {
 @Volatile private var lastChecks: StabilityCheckResult? = null
 fun snapshot(): DiagnosticSnapshot { val c = GradleMcConfig.current(); return DiagnosticSnapshot(Instant.now(), environment(), memory(), PerformanceService.snapshot(), c, latestReport(c), lastChecks) }
 fun statusLines() = snapshot().let { listOf("GradleMC ${it.environment.gradleMcVersion} on Fabric Loader ${it.environment.loaderVersion}", "Minecraft ${it.environment.minecraftVersion}; Java ${it.environment.javaVersion}", "${it.environment.operatingSystem}; ${it.environment.installedModCount} loaded mods") }
 fun memoryLine() = memory().let { "Memory: ${it.usedMiB} MiB / ${it.maxMiB} MiB (${String.format(Locale.ROOT, "%.1f", it.usedPercent)}%, ${it.pressure.name.lowercase()})" }
 fun runChecks(): StabilityCheckResult { val c = GradleMcConfig.current(); val m = memory(); val dir = directory(c); val findings = listOf(StabilityFinding(m.pressure,"Runtime memory snapshot","Used ${m.usedMiB} MiB, committed ${m.committedMiB} MiB, max ${m.maxMiB} MiB.",if(m.pressure.ordinal>=DiagnosticSeverity.WARN.ordinal) "Close memory-heavy applications or allocate more heap if this remains high." else ""), StabilityFinding(DiagnosticSeverity.PASS,"GradleMC configuration is valid","Reports use the '${c.reportDirectoryName}' directory."), reportDirectoryFinding(dir), StabilityFinding(if(Runtime.version().feature()>=17) DiagnosticSeverity.PASS else DiagnosticSeverity.FAIL,"Java runtime compatibility","Running Java ${Runtime.version().feature()}.","Minecraft 1.20.1 requires Java 17 or newer.")); return StabilityCheckResult(Instant.now(),findings).also { lastChecks=it } }
 private fun reportDirectoryFinding(dir: Path) = try { if (java.nio.file.Files.exists(dir) && (!java.nio.file.Files.isDirectory(dir) || java.nio.file.Files.isSymbolicLink(dir))) StabilityFinding(DiagnosticSeverity.FAIL,"Report output is unavailable","Unsafe report directory.","Check report directory permissions and remove unsafe filesystem links.") else StabilityFinding(if(java.nio.file.Files.exists(dir)) DiagnosticSeverity.PASS else DiagnosticSeverity.INFO,if(java.nio.file.Files.exists(dir)) "Report directory is writable" else "Report directory will be created on export",displayPath(dir)) } catch(e: Exception) { StabilityFinding(DiagnosticSeverity.FAIL,"Report output is unavailable",e.javaClass.simpleName) }
 fun exportReport(): ReportExportResult = try { val checks=runChecks(); val s=snapshot(); val d=directory(s.configuration); val paths=listOf(ReportFiles.write(d,"txt",DiagnosticsReportRenderer.text(s,checks)),ReportFiles.write(d,"json",DiagnosticsReportRenderer.json(s,checks))); ReportExportResult.Success(paths,paths.map(::displayPath)) } catch(e: Exception) { GradleMC.LOGGER.warn("GradleMC report export failed",e); ReportExportResult.Failure("Report export failed: ${e.message ?: e.javaClass.simpleName}",e) }
 fun latestReportResult(): LatestReportResult = try { ReportFiles.latest(directory(GradleMcConfig.current()))?.let { LatestReportResult.Found(it,displayPath(it)) } ?: LatestReportResult.Empty } catch(e: Exception) { LatestReportResult.Failure("Latest report lookup failed: ${e.message ?: e.javaClass.simpleName}") }
 fun smartScore()=smart(runChecks()); fun smartAdvice()=smart(runChecks())
 private fun smart(c: StabilityCheckResult): SmartDiagnosticsResult { val score=(100-c.findings.sumOf { when(it.severity){DiagnosticSeverity.CRITICAL->45;DiagnosticSeverity.FAIL->25;DiagnosticSeverity.WARN->10;else->0} }).coerceIn(0,100); val advice=c.findings.filter { it.severity.ordinal>=DiagnosticSeverity.WARN.ordinal }.map { it.suggestion.ifBlank { it.detail } }.distinct().ifEmpty { listOf("No shallow stability warnings are currently present.") }; return SmartDiagnosticsResult(score,advice,"This is a local score based only on GradleMC's implemented shallow checks; no telemetry or remote services are used.",c) }
 fun displayPath(path:Path)=path.toAbsolutePath().normalize().let { p -> val g=FabricLoader.getInstance().gameDir.toAbsolutePath().normalize(); if(p.startsWith(g)) "<gameDir>/${g.relativize(p).toString().replace('\\','/')}" else "<external>" }
 private fun latestReport(c:GradleMcConfigSnapshot)=ReportFiles.latest(directory(c)); private fun directory(c:GradleMcConfigSnapshot)=ReportPaths.reportDirectory(FabricLoader.getInstance().gameDir,c)
 private fun environment():EnvironmentSnapshot { val l=FabricLoader.getInstance(); return EnvironmentSnapshot(GradleMC.VERSION,runCatching { SharedConstants.getCurrentVersion().name }.getOrDefault(GradleMC.MINECRAFT_VERSION),l.getModContainer("fabricloader").orElseThrow().metadata.version.friendlyString,System.getProperty("java.version","unknown"),System.getProperty("java.vendor","unknown"),OperatingSystemInfoProvider.current().displayName,System.getProperty("os.arch","unknown"),if(l.environmentType==EnvType.CLIENT)"CLIENT" else "SERVER",l.allMods.size,l.allMods.map { "${it.metadata.id}:${it.metadata.version.friendlyString}" }.sorted()) }
 private fun memory():MemorySnapshot { val r=Runtime.getRuntime();val committed=r.totalMemory();val used=committed-r.freeMemory();val max=r.maxMemory();val p=if(max<=0)0.0 else used*100.0/max;return MemorySnapshot(used,committed,max,(max-used).coerceAtLeast(0),p,when{p>=95->DiagnosticSeverity.CRITICAL;p>=80->DiagnosticSeverity.WARN;else->DiagnosticSeverity.PASS},Instant.now()) }
}
internal object DiagnosticsReportRenderer { fun text(s:DiagnosticSnapshot,c:StabilityCheckResult)=buildString { appendLine("GradleMC Diagnostics Report");appendLine("Generated: ${s.collectedAt}");appendLine();appendLine("Environment");appendLine("GradleMC: ${s.environment.gradleMcVersion}");appendLine("Minecraft: ${s.environment.minecraftVersion}");appendLine("Fabric Loader: ${s.environment.loaderVersion}");appendLine("Java: ${s.environment.javaVersion} (${s.environment.javaVendor})");appendLine("Operating system: ${s.environment.operatingSystem}");appendLine("Installed mods: ${s.environment.installedModCount}");appendLine();appendLine("Memory");appendLine("Used: ${s.memory.usedMiB} MiB / ${s.memory.maxMiB} MiB (${String.format(Locale.ROOT,"%.1f",s.memory.usedPercent)}%)");appendLine();appendLine("Performance");appendLine("Performance mode: ${s.performance.mode.label}");appendLine("Rendered FPS: ${s.performance.currentFps?.let { String.format(Locale.ROOT,"%.1f",it) } ?: "not collected"}");appendLine("Average rendered FPS: ${s.performance.averageFps?.let { String.format(Locale.ROOT,"%.1f",it) } ?: "not collected"}");appendLine();appendLine("Stability checks (${c.summary})");c.findings.forEach { appendLine("[${it.severity}] ${it.title}: ${it.detail}") } }
 fun json(s: DiagnosticSnapshot, c: StabilityCheckResult): String {
    fun q(v: String) = "\"" + v.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\""
    val checks = c.findings.joinToString(",") { "{\"severity\":${q(it.severity.name)},\"title\":${q(it.title)},\"detail\":${q(it.detail)}}" }
    val percent = String.format(Locale.ROOT, "%.3f", s.memory.usedPercent)
    return "{\"format\":\"gradlemc-diagnostics-v1\",\"generatedAt\":${q(s.collectedAt.toString())},\"environment\":{\"loader\":\"Fabric\",\"gradleMcVersion\":${q(s.environment.gradleMcVersion)},\"minecraftVersion\":${q(s.environment.minecraftVersion)},\"fabricLoaderVersion\":${q(s.environment.loaderVersion)},\"javaVersion\":${q(s.environment.javaVersion)},\"javaVendor\":${q(s.environment.javaVendor)},\"modCount\":${s.environment.installedModCount}},\"memory\":{\"usedBytes\":${s.memory.usedBytes},\"maxBytes\":${s.memory.maxBytes},\"usedPercent\":$percent},\"checks\":[$checks]}"
 }
}
